import React,{useCallback,useEffect,useState} from 'react';
import styled from 'styled-components';
import toast from 'react-hot-toast';
import {MdAdd,MdPriceChange,MdVisibility,MdCheckCircle,MdCancel} from 'react-icons/md';
import service from '../services/supplierPriceUpdateService';
import organizationSupplierService from '../services/organizationSupplierService';
import organizationProductService from '../services/organizationProductService';
import {useApp} from '../context/AppContext';
import Button from '../components/Button';
import Modal from '../components/Modal';
import EmptyState from '../components/EmptyState';

const Page=styled.div`display:flex;flex-direction:column;gap:24px;`;
const Header=styled.header`display:flex;justify-content:space-between;align-items:flex-start;gap:16px;flex-wrap:wrap;`;
const Title=styled.h1`font-size:${({theme})=>theme.fontSizes['3xl']};color:${({theme})=>theme.colors.textPrimary};`;
const Subtitle=styled.p`color:${({theme})=>theme.colors.textSecondary};margin-top:4px;max-width:760px;`;
const List=styled.div`display:flex;flex-direction:column;gap:12px;`;
const Card=styled.article`background:${({theme})=>theme.colors.bgCard};border:1px solid ${({theme})=>theme.colors.border};border-radius:${({theme})=>theme.radii.lg};padding:16px;display:flex;justify-content:space-between;align-items:center;gap:14px;flex-wrap:wrap;strong{color:${({theme})=>theme.colors.textPrimary};}small{display:block;color:${({theme})=>theme.colors.textMuted};margin-top:4px;}`;
const Actions=styled.div`display:flex;gap:8px;flex-wrap:wrap;`;
const Badge=styled.span`display:inline-flex;padding:4px 8px;border-radius:999px;background:${({theme})=>theme.colors.infoLight};color:${({theme})=>theme.colors.info};font-size:12px;font-weight:700;`;
const Grid=styled.div`display:grid;grid-template-columns:1fr 1fr;gap:14px;@media(max-width:600px){grid-template-columns:1fr;}`;
const Field=styled.label`display:flex;flex-direction:column;gap:6px;color:${({theme})=>theme.colors.textSecondary};font-size:13px;font-weight:600;${({$wide})=>$wide?'grid-column:1/-1;':''}`;
const Input=styled.input`padding:10px;border:1px solid ${({theme})=>theme.colors.border};border-radius:${({theme})=>theme.radii.md};background:${({theme})=>theme.colors.bgInput};color:${({theme})=>theme.colors.textPrimary};`;
const Select=styled.select`padding:10px;border:1px solid ${({theme})=>theme.colors.border};border-radius:${({theme})=>theme.radii.md};background:${({theme})=>theme.colors.bgInput};color:${({theme})=>theme.colors.textPrimary};`;
const Notice=styled.div`padding:12px;border-radius:${({theme})=>theme.radii.md};background:${({theme})=>theme.colors.warningLight};color:${({theme})=>theme.colors.warning};font-size:13px;margin-bottom:14px;`;
const ScopeNotice=styled.div`padding:14px;border-radius:${({theme})=>theme.radii.md};background:${({theme})=>theme.colors.infoLight};color:${({theme})=>theme.colors.info};font-size:14px;strong{display:block;margin-bottom:4px;}`;
const Filters=styled.div`display:grid;grid-template-columns:minmax(220px,1fr) 180px 160px 160px;gap:10px;align-items:end;@media(max-width:900px){grid-template-columns:1fr 1fr;}@media(max-width:520px){grid-template-columns:1fr;}`;
const Pagination=styled.div`display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;color:${({theme})=>theme.colors.textSecondary};font-size:14px;`;
const PreviewRow=styled.div`padding:12px;background:${({theme})=>theme.colors.bgInput};border-radius:${({theme})=>theme.radii.md};margin-top:10px;color:${({theme})=>theme.colors.textPrimary};small{display:block;color:${({theme})=>theme.colors.textMuted};}`;
const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default function SupplierPriceUpdates(){
 const {state}=useApp(); const isAdmin=state.user?.role==='ADMIN';
 const [updates,setUpdates]=useState([]),[suppliers,setSuppliers]=useState([]),[products,setProducts]=useState([]);
 const [filters,setFilters]=useState({search:'',status:'',dateFrom:'',dateTo:''});
 const [pagination,setPagination]=useState({page:1,pageSize:20,totalItems:0,totalPages:0}),[listLoading,setListLoading]=useState(false);
 const [formOpen,setFormOpen]=useState(false),[previewOpen,setPreviewOpen]=useState(false),[preview,setPreview]=useState(null),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({organizationSupplierId:'',organizationProductId:'',commercialUnit:'caixa',unitsPerPackage:1,packagePrice:'',supplierCode:'',available:true,deliveryLeadDays:''});
 const load=useCallback(async(page=1)=>{setListLoading(true);try{const result=await service.list({page,pageSize:20,...Object.fromEntries(Object.entries(filters).filter(([,value])=>value))});setUpdates(result?.items||[]);setPagination(result?.pagination||{page:1,pageSize:20,totalItems:0,totalPages:0});}finally{setListLoading(false);}},[filters]);
 useEffect(()=>{const timer=setTimeout(()=>load(1).catch(()=>{}),300);return()=>clearTimeout(timer);},[load,state.establishment?.id]);
 const openCreate=async()=>{setSaving(true);try{if(!suppliers.length||!products.length){const[s,p]=await Promise.all([organizationSupplierService.list(),organizationProductService.list()]);setSuppliers((s||[]).filter(x=>x.isActive));setProducts((p||[]).filter(x=>x.isActive));}setFormOpen(true);}finally{setSaving(false);}};
 const submit=async e=>{e.preventDefault();setSaving(true);try{await service.create({organizationSupplierId:form.organizationSupplierId,note:null,items:[{organizationProductId:form.organizationProductId,supplierCode:form.supplierCode||null,commercialUnit:form.commercialUnit,unitsPerPackage:Number(form.unitsPerPackage),packagePrice:Number(form.packagePrice),available:form.available,deliveryLeadDays:form.deliveryLeadDays===''?null:Number(form.deliveryLeadDays)}]});toast.success('Lote enviado para aprovação.');setFormOpen(false);await load(1);}finally{setSaving(false);}};
 const showPreview=async item=>{setPreview(await service.preview(item.id));setPreviewOpen(true);};
 const affectedEstablishments=[...new Set((preview?.items||[]).flatMap(item=>item.affectedLinks.map(link=>link.establishment)))];
 const affectedLinks=(preview?.items||[]).reduce((total,item)=>total+item.affectedLinks.length,0);
 const apply=async()=>{if(!window.confirm(`Aprovar uma única vez para todo o grupo?\n\n${affectedLinks} vínculo(s) em ${affectedEstablishments.length} estabelecimento(s) serão atualizados.`))return;setSaving(true);try{const result=await service.apply(preview.id);toast.success(`Lote central aplicado em ${result.affectedLinks||0} vínculo(s).`);setPreviewOpen(false);await load(pagination.page);}finally{setSaving(false);}};
 const reject=async item=>{const reason=window.prompt('Motivo da rejeição:');if(!reason)return;await service.reject(item.id,reason);toast.success('Lote rejeitado.');await load(pagination.page);};
 return <Page><Header><div><Title>Atualizações de Preços</Title><Subtitle>Catálogo central, prévia de impacto e propagação controlada para vínculos locais já autorizados.</Subtitle></div>{isAdmin&&<Button disabled={saving} onClick={openCreate}><MdAdd/>Novo lote</Button>}</Header><ScopeNotice><strong>Aprovação central do grupo</strong>Uma única aprovação aplica os preços a todos os estabelecimentos vinculados da organização. Não é necessário aprovar estabelecimento por estabelecimento.</ScopeNotice>
 <Filters><Field>Buscar fornecedor<Input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="Nome do fornecedor"/></Field><Field>Status<Select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos</option><option value="SUBMITTED">Enviados</option><option value="APPLIED">Aplicados</option><option value="REJECTED">Rejeitados</option><option value="DRAFT">Rascunhos</option></Select></Field><Field>De<Input type="date" value={filters.dateFrom} onChange={e=>setFilters({...filters,dateFrom:e.target.value})}/></Field><Field>Até<Input type="date" value={filters.dateTo} onChange={e=>setFilters({...filters,dateTo:e.target.value})}/></Field></Filters>
 {listLoading?<Notice>Carregando atualizações...</Notice>:!updates.length?<EmptyState icon={<MdPriceChange/>} title="Nenhum lote de preços" subtitle="Nenhuma atualização corresponde aos filtros informados."/>:<List>{updates.map(item=><Card key={item.id}><div><strong>{item.organizationSupplier.name}</strong><small>{new Date(item.createdAt).toLocaleString('pt-BR')} · {item._count?.items||0} item(ns)</small></div><Actions><Badge>{item.status}</Badge><Button size="sm" variant="secondary" onClick={()=>showPreview(item)}><MdVisibility/>Prévia</Button>{isAdmin&&item.status==='SUBMITTED'&&<Button size="sm" variant="ghost" onClick={()=>reject(item)}><MdCancel/>Rejeitar</Button>}</Actions></Card>)}</List>}
 <Pagination><span>{pagination.totalItems} registro(s) · Página {pagination.page} de {pagination.totalPages||1}</span><Actions><Button size="sm" variant="secondary" disabled={listLoading||pagination.page<=1} onClick={()=>load(pagination.page-1)}>Anterior</Button><Button size="sm" variant="secondary" disabled={listLoading||pagination.page>=pagination.totalPages} onClick={()=>load(pagination.page+1)}>Próxima</Button></Actions></Pagination>
 <Modal isOpen={formOpen} onClose={()=>setFormOpen(false)} title="Novo lote de preço" maxWidth="760px" footer={<><Button variant="secondary" onClick={()=>setFormOpen(false)}>Cancelar</Button><Button disabled={saving} onClick={submit}>Enviar para aprovação</Button></>}><Notice>O lote não cria vínculos produto-fornecedor. Somente relações locais existentes poderão receber o preço aprovado.</Notice><form onSubmit={submit}><Grid><Field $wide>Fornecedor central<Select required value={form.organizationSupplierId} onChange={e=>setForm({...form,organizationSupplierId:e.target.value})}><option value="">Selecione</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field $wide>Produto central<Select required value={form.organizationProductId} onChange={e=>setForm({...form,organizationProductId:e.target.value})}><option value="">Selecione</option>{products.map(x=><option key={x.id} value={x.id}>{x.internalCode} — {x.name}</option>)}</Select></Field><Field>Unidade comercial<Input required value={form.commercialUnit} onChange={e=>setForm({...form,commercialUnit:e.target.value})}/></Field><Field>Unidades por embalagem<Input required type="number" min="0.001" step="0.001" value={form.unitsPerPackage} onChange={e=>setForm({...form,unitsPerPackage:e.target.value})}/></Field><Field>Preço do pacote<Input required type="number" min="0.01" step="0.01" value={form.packagePrice} onChange={e=>setForm({...form,packagePrice:e.target.value})}/></Field><Field>Prazo de entrega (dias)<Input type="number" min="0" value={form.deliveryLeadDays} onChange={e=>setForm({...form,deliveryLeadDays:e.target.value})}/></Field><Field $wide>Código no fornecedor<Input value={form.supplierCode} onChange={e=>setForm({...form,supplierCode:e.target.value})}/></Field></Grid></form></Modal>
 <Modal isOpen={previewOpen} onClose={()=>setPreviewOpen(false)} title="Prévia central do lote" maxWidth="900px" footer={isAdmin&&preview?.status==='SUBMITTED'?<><Button variant="secondary" onClick={()=>setPreviewOpen(false)}>Fechar</Button><Button disabled={saving||affectedLinks===0} onClick={apply}><MdCheckCircle/>Aprovar para todo o grupo</Button></>:null}><Notice>Impacto organizacional: {affectedLinks} vínculo(s) em {affectedEstablishments.length} estabelecimento(s). A aplicação grava histórico e não altera custo atual, estoque ou fichas técnicas.</Notice>{affectedLinks===0&&<Notice>Este lote não possui vínculos locais elegíveis e não pode ser aplicado.</Notice>}{(preview?.items||[]).map(item=><PreviewRow key={item.id}><strong>{item.product.internalCode} — {item.product.name}</strong><small>{money(item.previousPackagePrice)} → {money(item.newPackagePrice)} · normalizado {money(item.newNormalizedPrice)} · variação {item.percentageVariation===null?'nova oferta':`${item.percentageVariation.toFixed(2)}%`} · {item.affectedLinks.length} vínculo(s)</small>{item.affectedLinks.map(link=><small key={link.productSupplierId}>{link.establishment}: {link.product} / {link.supplier} — atual {money(link.currentPrice)}</small>)}</PreviewRow>)}</Modal>
 </Page>;
}
